@startuml

abstract class Forms #80BA9D {
    --Method--
    {abstract} getPerimetre();
    {abstract} getAire();
}

class Circle #9BD1A7 {
    --Attribute--
    -rayon:double;
    --Method--
    +getPerimetre(): double;
    +getAire(): double;
    +toString(): String;
    +getDiametre(): double;
    +getRayon(): double;
    +setRayon(rayon:double);
    --Constructor--
    +Circle();
    +Circle(rayon:double);
}

class Rectangle #9BD1A7 {
    --Attribute--
    -largeur:double;
    -longueur:double;
    --Method--
    +getPerimetre(): double;
    +getAire(): double;
    +toString(): String;
    +getLargeur(): double;
    +setLargeur(largeur:double);
    +getLongueur(): double;
    +setLongueur(longueur:double);
    --Constructor--
    +Rectangle();
    +Rectangle(largeur:double, longueur:double);
}

class Triangle #9BD1A7 {
    --Attribute--
    -base:double;
    -longueur:double;
    --Method--
    +getPerimetre(): double;
    +getAire(): double;
    +toString(): String;
    +getBase(): double;
    +setBase(base:double);
    +getLongueur(): double;
    +setLongueur(longueur:double);
    --Constructor--
    +Triangle();
    +Triangle(base:double, longueur:double);
}

class FormsComposite #9BD1A7 {
    --Attribute--
    -myAllForms:List<Form>;
    --Method--
    +getPerimetre(): double;
    +getAire(): double;
    +addForm(forms:Forms);
    +removeForm(forms:Forms);
    +toString(): String;
    --Constructor--
    +FormsComposite(List<Form> myAllForms);
}

Forms <|-- Circle #6CBB7A
Forms <|-- Rectangle #6CBB7A
Forms <|-- Triangle #6CBB7A
Forms <|-- FormsComposite #6CBB7A
Forms "*" <-- FormsComposite #6CBB7A

@enduml